AUGMENTATION: True
IMAGE_SIZE: [224,224,3] # for vgg 16 model <- documentation
BATCH_SIZE: 32
INCLUDE_TOP: False # to remove top from layers
EPOCHS: 5
CLASSES: 4
WEIGHTS: imagenet 
LEARNING_RATE: 0.01
